services:
  api:
    build: ./
    container_name: secure_api
    ports:
      - "3000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env
    networks:
      - secure_api_bank


networks:
  secure_api_bank:
    driver: bridge